# Background / foreground
background #1a1b26
foreground #BBD8F2

# Cursor
cursor #A2CDF2
cursor_text_color #101A26

# Selection
selection_background #364A73
selection_foreground #BBD8F2

# Black
color0 #101A26
color8 #364A73

# Red (erreurs)
color1 #D98C8C
color9 #F2AAAA

# Green (succès)
color2 #9CCFA8
color10 #B8E6B8

# Yellow (warnings)
color3 #D8C58A
color11 #F0DDA6

# Blue
color4 #586F8C
color12 #A2CDF2

# Magenta
color5 #B69ACB
color13 #D7B8F2

# Cyan
color6 #8FC7D9
color14 #BBD8F2

# White
color7 #BBD8F2
color15 #E5F2FF
