# https://www.reddit.com/r/unixporn/comments/hjzw5f/oc_qualitative_color_palette_for_ansi_terminal/
# Special
foreground            #C0C0C0
background            #101010
cursor                #C0C0C0
cursor_text_color     #101010
selection_foreground  #101010
selection_background  #C0C0C0

# Black / Dark gray
color0   #101010
color8   #454545

# Red / Orange
color1   #EFA6A2
color9   #E0AF85

# Green / Aquamarine
color2   #80C990
color10  #5ACCAF

# Amber / Yellow
color3   #A69460
color11  #C8C874

# Blue / Violet
color4   #A3B8EF
color12  #CCACED

# Magenta / Rose
color5   #E6A3DC
color13  #F2A1C2

# Cyan / Azure
color6   #50CACD
color14  #74C3E4

# Gray / White
color7   #808080
color15  #C0C0C0
