# general

general {
    hide_cursor = true
    ignore_empty_input = true
}

# bg

background {
    monitor =
    path = ./JRTT.jpg
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.5
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# clock

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(ffffffee)

    font_size = 85
    font_family = Inter

    position = -750, 220
    halign = center
    valign = center
}

# date

label {
    monitor =
    text = cmd[update:60000] echo "$(LC_TIME=ja_JP.utf8 date '+%A, %d %B')"
    color = rgba(ffffffaa)

    font_size = 22
    font_family = Maple Mono NF CN

    position = -750, 125
    halign = center
    valign = center
}

# user

label {
    monitor =
    text = こんにちは
    color = rgba(ffffffff)

    font_size = 20
    font_family = Maple Mono NF CN

    position = -750, 60
    halign = center
    valign = center
}

# password

input-field {
    monitor =

    size = 320, 58
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true

    outer_color = rgba(ffffffff)
    inner_color = rgba(00000055)
    font_color = rgba(ffffffff)

    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff88">パスワード</span>

    hide_input = false

    position = -750, -15
    halign = center
    valign = center

    rounding = 10
}

# caps lock
shape {
    monitor =
    color = rgba(00000066)
    size = 220, 40
    rounding = 12
    position = -750, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "caps lock: $(hyprctl devices -j | jq -r '.keyboards[] | select(.main == true) | .capsLock')"
    color = rgba(ffffff99)

    font_size = 14
    font_family = Maple Mono NF CN Italic

    position = -750, -80
    halign = center
    valign = center
}
