#!/usr/bin/env bash

set -euo pipefail

THEMES_DIR="$HOME/.config/themes"
CURRENT="$THEMES_DIR/current"

die() {
    echo "Error: $*" >&2
    exit 1
}

usage() {
    echo "Usage: $(basename "$0") <theme>"
    echo
    echo "Available themes:"

    for theme in "$THEMES_DIR"/*/; do
        [[ -d "$theme" ]] || continue

        name="$(basename "$theme")"
        [[ "$name" == "current" ]] && continue

        echo "  - $name"
    done
}

[[ -d "$THEMES_DIR" ]] || die "Themes directory not found"

if [[ $# -ne 1 ]]; then
    usage
    exit 1
fi

THEME="$1"

THEME_DIR="$THEMES_DIR/$THEME"

[[ -d "$THEME_DIR" ]] || die "Theme '$THEME' does not exist"

echo "switching theme to: $THEME"

# Current theme
ln -sfn "$THEME_DIR" "$CURRENT"

echo "  ✓ current -> $THEME"

# Symlinks
for app_dir in "$THEME_DIR"/*; do
    [[ -d "$app_dir" ]] || continue

    app="$(basename "$app_dir")"
    target_dir="$HOME/.config/$app"

    # Crée le dossier si nécessaire
    mkdir -p "$target_dir"

    for file in "$app_dir"/*; do
        [[ -f "$file" ]] || continue

        filename="$(basename "$file")"

        rm -f "$target_dir/$filename"

        ln -s "$CURRENT/$app/$filename" \
              "$target_dir/$filename"

        echo "  ✓ $app/$filename"
    done
done

# Reload Hyprland
if command -v hyprctl >/dev/null 2>&1; then
    hyprctl reload >/dev/null 2>&1 || true
    echo "  ✓ hyprland reloaded"
fi

# Reload Hyprpaperr
if command -v hyprpaper >/dev/null 2>&1; then
    pkill -x hyprpaper 2>/dev/null || true
    sleep 0.2
    hyprpaper >/dev/null 2>&1 & disown
    echo "  ✓ hyprpaper reloaded"
fi

# Restart Waybar
if command -v waybar >/dev/null 2>&1; then
    pkill -x waybar 2>/dev/null || true
    sleep 0.2
    waybar >/dev/null 2>&1 & disown
    echo "  ✓ waybar restarted"
fi

# Reload wal according to the selected theme

WAL_THEME=$THEME

if [ "$WAL_THEME" = "supaS" ]; then
    wal --theme "$WAL_THEME" -l >/dev/null 2>&1
else
    wal --theme "$WAL_THEME" >/dev/null 2>&1
fi

echo "  ✓ wal reloaded with theme '$WAL_THEME'"

/home/nino-nakano/Projets/pywalium/generate.sh >/dev/null 2>&1
echo "  ✓ chrome theme refreshed"


# Get Chromium's current workspace

CHROME_WS=$(hyprctl clients -j | jq -r '
    .[] | select(.class == "chromium") | .workspace.id
' | head -n1)

if ! pgrep -x "chromium" >/dev/null 2>&1; then
    echo "  ✓ chromium is not running, skipping restart"
    echo "theme switched to '$THEME'."
    exit 0
else
    # Restart Chromium
    pkill -x chromium 2>/dev/null || true
    hyprctl dispatch 'hl.dsp.exec_cmd("chromium --force-device-scale-factor:0.8", { workspace = "'$CHROME_WS' silent" })' >/dev/null 2>&1
    echo "  ✓ chromium restarted on workspace $CHROME_WS"
fi


echo "theme switched to '$THEME'."
